import type {
  BassStyle,
  ChordExtension,
  ChordRhythm,
  Genre,
  PartType,
  RiffStyle,
  ScaleId,
  TimeSignature,
} from '../types'
import type { DrumFillId, DrumPatternId } from './drumPatterns'

type Weights<K extends string> = Partial<Record<K, number>>

export interface GenreDef {
  /** Typical tempo range; the default BPM sits inside it. */
  bpm: readonly [number, number]
  defaultBpm: number
  /** Default swing 0–1. */
  swing: number
  /** Subdivision the swing applies to: 8 for shuffle/jazz feels, 16 otherwise. */
  swingGrid: 8 | 16
  timeSignature: TimeSignature
  /** Parts enabled by default in multitrack mode. */
  parts: readonly PartType[]
  scales: Weights<ScaleId>
  /** Chance of using the Markov chain instead of a preset progression. */
  markovChance: number
  progressions: Readonly<Record<string, number>>
  /** End Markov progressions with V → I instead of looping smoothly. */
  authenticCadence?: boolean
  chordsPerBar: Weights<'0.5' | '1' | '2'>
  extensions: Weights<ChordExtension>
  padExtensions: Weights<ChordExtension>
  chordRhythms: Weights<ChordRhythm>
  bassStyles: Weights<BassStyle>
  riffStyles: Weights<RiffStyle>
  drums: Weights<DrumPatternId>
  /** Pattern for 3/4 and 6/8. */
  compoundDrums: DrumPatternId
  fills: Weights<DrumFillId>
  /** Base note density multiplier for melodic parts. */
  density: number
  /** Melody rhythm grid: 8 = mostly eighths, 16 = sixteenths allowed. */
  melodyGrid: 8 | 16
}

const FOUR_FOUR = { numerator: 4, denominator: 4 }

const METAL_COMMON = {
  swing: 0,
  swingGrid: 16,
  timeSignature: FOUR_FOUR,
  parts: ['drums', 'bass', 'riff'],
  extensions: { power: 4, triad: 1 },
  padExtensions: { triad: 2, sus2: 1 },
  chordRhythms: { sustain: 1, stabs: 2 },
  bassStyles: { riff: 1 },
  compoundDrums: 'sixEightMetal',
  density: 1,
  melodyGrid: 16,
} as const satisfies Partial<GenreDef>

export const GENRES_DEF: Record<Genre, GenreDef> = {
  pop: {
    bpm: [95, 125],
    defaultBpm: 110,
    swing: 0,
    swingGrid: 16,
    timeSignature: FOUR_FOUR,
    parts: ['drums', 'bass', 'chords', 'melody'],
    scales: { major: 3, minor: 2, mixolydian: 0.5 },
    markovChance: 0.4,
    progressions: { axis: 3, sensitive: 3, doowop: 2, royalRoad: 1, epicMinor: 2, minorDescent: 1, minorPlagal: 1 },
    chordsPerBar: { '1': 3, '2': 1 },
    extensions: { triad: 3, add9: 2, sus2: 1 },
    padExtensions: { add9: 2, sus2: 1 },
    chordRhythms: { sustain: 2, stabs: 1, syncopated: 2, strum: 1 },
    bassStyles: { root: 2, octave: 1, syncopated: 1 },
    riffStyles: { groove: 1 },
    drums: { pop: 1 },
    compoundDrums: 'sixEight',
    fills: { snareRoll: 2, tomsShort: 1 },
    density: 1,
    melodyGrid: 16,
  },
  hipHop: {
    bpm: [80, 100],
    defaultBpm: 90,
    swing: 0.3,
    swingGrid: 16,
    timeSignature: FOUR_FOUR,
    parts: ['drums', 'bass', 'chords', 'melody'],
    scales: { minor: 3, dorian: 2, phrygian: 1, harmonicMinor: 1 },
    markovChance: 0.3,
    progressions: { minorVamp: 3, lofiMinor: 1, epicMinor: 1, sensitive: 1, jazzTwoFiveOne: 0.5, harmonicMinor: 1 },
    chordsPerBar: { '1': 2, '0.5': 1 },
    extensions: { seventh: 3, ninth: 1 },
    padExtensions: { seventh: 1, ninth: 1 },
    chordRhythms: { sustain: 2, stabs: 1 },
    bassStyles: { sub808: 3, root: 1 },
    riffStyles: { groove: 1 },
    drums: { boomBap: 1 },
    compoundDrums: 'sixEight',
    fills: { snareRoll: 1 },
    density: 0.85,
    melodyGrid: 16,
  },
  lofi: {
    bpm: [70, 90],
    defaultBpm: 80,
    swing: 0.5,
    swingGrid: 16,
    timeSignature: FOUR_FOUR,
    parts: ['drums', 'bass', 'chords', 'melody'],
    scales: { major: 1, minor: 2, dorian: 2 },
    markovChance: 0.3,
    progressions: { lofiDescent: 3, lofiMinor: 3, jazzTwoFiveOne: 2, jazzTurnaround: 1, minorVamp: 1 },
    chordsPerBar: { '1': 2, '0.5': 1 },
    extensions: { seventh: 2, ninth: 3 },
    padExtensions: { ninth: 1, add9: 1 },
    chordRhythms: { sustain: 3, syncopated: 1 },
    bassStyles: { root: 2, walking: 0.5 },
    riffStyles: { groove: 1 },
    drums: { lofi: 1 },
    compoundDrums: 'jazzWaltz',
    fills: { jazzFill: 1 },
    density: 0.7,
    melodyGrid: 8,
  },
  house: {
    bpm: [120, 128],
    defaultBpm: 124,
    swing: 0.1,
    swingGrid: 16,
    timeSignature: FOUR_FOUR,
    parts: ['drums', 'bass', 'chords', 'melody'],
    scales: { minor: 2, dorian: 2, major: 1 },
    markovChance: 0.4,
    progressions: { minorVamp: 2, sensitive: 1, epicMinor: 1, axis: 1, dorianVamp: 1 },
    chordsPerBar: { '1': 2, '0.5': 1 },
    extensions: { seventh: 3, ninth: 1 },
    padExtensions: { seventh: 1, sus2: 1 },
    chordRhythms: { stabs: 3, syncopated: 2 },
    bassStyles: { offbeat: 3, syncopated: 1 },
    riffStyles: { groove: 1 },
    drums: { house: 1 },
    compoundDrums: 'sixEightElectronic',
    fills: { electronicRiser: 2, snareRoll: 1 },
    density: 0.9,
    melodyGrid: 16,
  },
  techno: {
    bpm: [125, 140],
    defaultBpm: 130,
    swing: 0,
    swingGrid: 16,
    timeSignature: FOUR_FOUR,
    parts: ['drums', 'bass', 'arp'],
    scales: { minor: 2, phrygian: 2, dorian: 1 },
    markovChance: 0.3,
    progressions: { ambientMinor: 2, phrygianMetal: 1, minorVamp: 2, dorianVamp: 1 },
    chordsPerBar: { '0.5': 2, '1': 1 },
    extensions: { triad: 1, sus2: 1, seventh: 1 },
    padExtensions: { sus2: 1, triad: 1 },
    chordRhythms: { stabs: 2, sustain: 1 },
    bassStyles: { root: 2, offbeat: 1, syncopated: 1 },
    riffStyles: { tremolo: 1 },
    drums: { techno: 1 },
    compoundDrums: 'sixEightElectronic',
    fills: { electronicRiser: 2, snareBuild: 1 },
    density: 0.9,
    melodyGrid: 16,
  },
  dnb: {
    bpm: [165, 178],
    defaultBpm: 174,
    swing: 0,
    swingGrid: 16,
    timeSignature: FOUR_FOUR,
    parts: ['drums', 'bass', 'pad', 'melody'],
    scales: { minor: 3, dorian: 1, harmonicMinor: 1 },
    markovChance: 0.4,
    progressions: { epicMinor: 2, minorDescent: 2, lofiMinor: 1, ambientMinor: 1 },
    chordsPerBar: { '0.5': 2, '1': 1 },
    extensions: { seventh: 2, ninth: 2 },
    padExtensions: { ninth: 2, seventh: 1 },
    chordRhythms: { sustain: 3 },
    bassStyles: { sub808: 1, root: 1, syncopated: 1 },
    riffStyles: { groove: 1 },
    drums: { dnb: 1 },
    compoundDrums: 'sixEightElectronic',
    fills: { snareRoll: 2, snareBuild: 1 },
    density: 0.8,
    melodyGrid: 8,
  },
  rock: {
    bpm: [100, 140],
    defaultBpm: 120,
    swing: 0,
    swingGrid: 16,
    timeSignature: FOUR_FOUR,
    parts: ['drums', 'bass', 'chords', 'melody'],
    scales: { major: 2, minor: 2, mixolydian: 2, minorPentatonic: 1 },
    markovChance: 0.35,
    progressions: { classicRock: 3, mixolydianRock: 3, axis: 2, epicMinor: 1, minorPlagal: 1, twelveBar: 1 },
    chordsPerBar: { '1': 3, '2': 1 },
    extensions: { triad: 2, power: 2 },
    padExtensions: { triad: 1 },
    chordRhythms: { strum: 2, sustain: 1, stabs: 1 },
    bassStyles: { root: 3, octave: 1 },
    riffStyles: { groove: 2, chug: 1 },
    drums: { rock: 1 },
    compoundDrums: 'sixEight',
    fills: { tomsDown: 2, snareRoll: 1, tomsShort: 1 },
    density: 1,
    melodyGrid: 8,
  },
  metal: {
    ...METAL_COMMON,
    bpm: [100, 160],
    defaultBpm: 140,
    scales: { minor: 2, phrygian: 2, harmonicMinor: 1, phrygianDominant: 1 },
    markovChance: 0.2,
    progressions: { phrygianMetal: 2, metalRise: 3, epicMinor: 2, harmonicMinor: 1, andalusian: 1 },
    chordsPerBar: { '1': 2, '0.5': 1 },
    riffStyles: { chug: 3, gallop: 2, tremolo: 1 },
    drums: { doubleKick: 2, metalBasic: 1 },
    fills: { tomsDown: 2, metalTriplets: 1, snareRoll: 1 },
  },
  deathMetal: {
    ...METAL_COMMON,
    bpm: [160, 220],
    defaultBpm: 190,
    scales: { phrygian: 3, locrian: 2, minor: 1, harmonicMinor: 1 },
    markovChance: 0.1,
    progressions: { tritone: 3, phrygianMetal: 2, chromaticTension: 2, doom: 1 },
    chordsPerBar: { '1': 2, '2': 1 },
    riffStyles: { tremolo: 3, chug: 2 },
    drums: { blast: 3, doubleKick: 2 },
    fills: { metalTriplets: 2, tomsDown: 1 },
  },
  stonerRock: {
    ...METAL_COMMON,
    bpm: [70, 110],
    defaultBpm: 90,
    swing: 0.25,
    swingGrid: 8,
    scales: { blues: 3, minorPentatonic: 2, mixolydian: 1, dorian: 1 },
    markovChance: 0.15,
    progressions: { stoner: 3, mixolydianRock: 2, twelveBar: 2, minorPlagal: 1 },
    chordsPerBar: { '1': 2, '0.5': 1 },
    riffStyles: { groove: 3, halfTime: 1 },
    drums: { stoner: 1 },
    compoundDrums: 'sixEight',
    fills: { tomsDown: 2, tomsShort: 1 },
    melodyGrid: 8,
  },
  doomMetal: {
    ...METAL_COMMON,
    bpm: [50, 80],
    defaultBpm: 65,
    parts: ['drums', 'bass', 'riff', 'pad'],
    scales: { phrygian: 2, minor: 2, harmonicMinor: 2 },
    markovChance: 0.15,
    progressions: { doom: 3, phrygianMetal: 2, harmonicMinor: 1, ambientMinor: 1 },
    chordsPerBar: { '0.5': 3, '1': 1 },
    riffStyles: { halfTime: 3, chug: 1 },
    drums: { doom: 1 },
    fills: { tomsDown: 2, tomsShort: 1 },
    density: 0.7,
    melodyGrid: 8,
  },
  thrashMetal: {
    ...METAL_COMMON,
    bpm: [160, 220],
    defaultBpm: 180,
    scales: { phrygian: 3, minor: 2, locrian: 1 },
    markovChance: 0.1,
    progressions: { phrygianMetal: 3, chromaticTension: 2, tritone: 1, metalRise: 1 },
    chordsPerBar: { '1': 2, '2': 1 },
    riffStyles: { gallop: 3, chug: 2, tremolo: 1 },
    drums: { skank: 3, gallop: 2, doubleKick: 1 },
    fills: { metalTriplets: 1, tomsDown: 1, snareRoll: 1 },
  },
  jazz: {
    bpm: [90, 200],
    defaultBpm: 130,
    swing: 0.66,
    swingGrid: 8,
    timeSignature: FOUR_FOUR,
    parts: ['drums', 'bass', 'chords', 'melody'],
    scales: { major: 3, dorian: 2, minor: 1, melodicMinor: 1 },
    markovChance: 0.3,
    authenticCadence: true,
    progressions: { jazzTwoFiveOne: 3, jazzTurnaround: 3, jazzMinorTwoFive: 2 },
    chordsPerBar: { '1': 2, '2': 1 },
    extensions: { seventh: 2, ninth: 3, thirteenth: 1 },
    padExtensions: { ninth: 1 },
    chordRhythms: { syncopated: 3, stabs: 1 },
    bassStyles: { walking: 1 },
    riffStyles: { groove: 1 },
    drums: { jazzSwing: 1 },
    compoundDrums: 'jazzWaltz',
    fills: { jazzFill: 1 },
    density: 0.9,
    melodyGrid: 8,
  },
  funk: {
    bpm: [95, 115],
    defaultBpm: 105,
    swing: 0.15,
    swingGrid: 16,
    timeSignature: FOUR_FOUR,
    parts: ['drums', 'bass', 'chords', 'melody'],
    scales: { dorian: 3, mixolydian: 2, minorPentatonic: 1 },
    markovChance: 0.2,
    progressions: { funkVamp: 3, dorianVamp: 3, minorVamp: 2, twelveBar: 1 },
    chordsPerBar: { '0.5': 2, '1': 1 },
    extensions: { ninth: 3, seventh: 2 },
    padExtensions: { seventh: 1 },
    chordRhythms: { stabs: 3, syncopated: 2 },
    bassStyles: { syncopated: 3, octave: 2 },
    riffStyles: { groove: 1 },
    drums: { funk: 1 },
    compoundDrums: 'sixEight',
    fills: { snareRoll: 1, tomsShort: 1 },
    density: 1.1,
    melodyGrid: 16,
  },
  ambient: {
    bpm: [60, 90],
    defaultBpm: 72,
    swing: 0,
    swingGrid: 16,
    timeSignature: FOUR_FOUR,
    parts: ['pad', 'arp', 'melody', 'bass'],
    scales: { lydian: 3, major: 2, dorian: 1, minor: 1 },
    markovChance: 0.5,
    progressions: { lydianFloat: 2, ambientMinor: 2, romantic: 1 },
    chordsPerBar: { '0.5': 3, '1': 1 },
    extensions: { add9: 2, sus2: 2, ninth: 2 },
    padExtensions: { add9: 2, ninth: 2, sus2: 1 },
    chordRhythms: { sustain: 1 },
    bassStyles: { root: 1 },
    riffStyles: { halfTime: 1 },
    drums: { ambient: 1 },
    compoundDrums: 'waltz',
    fills: { jazzFill: 1 },
    density: 0.5,
    melodyGrid: 8,
  },
}

/** Values the UI applies when the user picks a genre. */
export function genreDefaults(genre: Genre) {
  const g = GENRES_DEF[genre]
  return { bpm: g.defaultBpm, swing: g.swing, timeSignature: g.timeSignature, parts: g.parts }
}
